[package]
name = "s71085558"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.1.0"
schemars = "0.8.8"
serde = "1.0.136"
serde_json = "1.0"
